wandb_version: 1

activation:
  value: sigmoid
base_gamma:
  value: None
batch_size:
  value: 1
compute_fairness:
  value: true
compute_mode:
  value: default
constraint_type:
  value: node
dataset:
  value: adult
depth:
  value: 4
encoder_model:
  value: instructor
gradient_type:
  value: vanilla
lambda_const:
  value: 10
max_iter:
  value: 1
mode:
  value: node
model_type:
  value: mlp
num_trees:
  value: 3
offline_loss_type:
  value: mmd
probability:
  value: 0.5
reservoir_size:
  value: 500
