_wandb:
    value:
        cli_version: 0.24.0
        e:
            l92m2nyacv5rjbnfh8zo0a5982y9cpt5:
                args:
                    - --activation=sigmoid
                    - --base_gamma=None
                    - --batch_size=1
                    - --compute_fairness=True
                    - --compute_mode=default
                    - --constraint_type=node
                    - --dataset=adult
                    - --depth=4
                    - --encoder_model=instructor
                    - --gradient_type=vanilla
                    - --lambda_const=0
                    - --max_iter=1
                    - --mode=node
                    - --model_type=aranyani
                    - --num_trees=3
                    - --offline_loss_type=mmd
                    - --probability=0.5
                    - --reservoir_size=500
                codePath: main.py
                codePathLocal: cli.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1005867986944"
                        used: "144355643392"
                email: tjcsilva04@gmail.com
                executable: /home/tiago/anaconda3/envs/arnya/bin/python
                host: tiago-Modern-14-B5M
                memory:
                    total: "16092151808"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.17
                program: cli.py
                python: CPython 3.8.20
                root: /home/tiago/Documents/Bolsa/Aranyani2.0/src
                startedAt: "2026-01-20T22:46:28.181553Z"
                writerId: l92m2nyacv5rjbnfh8zo0a5982y9cpt5
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 3
                - 5
                - 53
            "2":
                - 3
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
                - 18
            "4": 3.8.20
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
activation:
    value: sigmoid
base_gamma:
    value: None
batch_size:
    value: 1
compute_fairness:
    value: true
compute_mode:
    value: default
constraint_type:
    value: node
dataset:
    value: adult
depth:
    value: 4
encoder_model:
    value: instructor
gradient_type:
    value: vanilla
lambda_const:
    value: 0
max_iter:
    value: 1
method:
    value: grid
mode:
    value: node
model_type:
    value: aranyani
name:
    value: sweep
num_trees:
    value: 3
offline_loss_type:
    value: mmd
parameters:
    value:
        activation:
            values:
                - sigmoid
        base_gamma:
            values:
                - None
        batch_size:
            values:
                - 1
        compute_fairness:
            values:
                - true
        compute_mode:
            values:
                - default
        constraint_type:
            values:
                - node
        dataset:
            values:
                - adult
        depth:
            values:
                - 4
        encoder_model:
            values:
                - instructor
        gradient_type:
            values:
                - vanilla
        lambda_const:
            values:
                - 0
        max_iter:
            values:
                - 1
        mode:
            values:
                - node
        model_type:
            values:
                - aranyani
        num_trees:
            values:
                - 3
        offline_loss_type:
            values:
                - mmd
        probability:
            values:
                - 0.5
        reservoir_size:
            values:
                - 500
probability:
    value: 0.5
program:
    value: cli.py
reservoir_size:
    value: 500
